@startuml
class Laberinto {
  +matriz: ElementoLaberinto[][]
  +dibujarLaberinto()
  +jugadorLlegoASalida()
}

class ElementoLaberinto {
  +descripcion()
}

class Pared {
  +descripcion()
}

class EspacioLibre {
  +descripcion()
}

Laberinto --> ElementoLaberinto : contiene
Laberinto --|> Pared
Laberinto --|> EspacioLibre
ElementoLaberinto <|-- Pared
ElementoLaberinto <|-- EspacioLibre
@enduml
