@startuml
left to right direction

class Laberinto {
  +matriz: ElementoLaberinto[][]
  +MostrarLaberinto()
}

class ElementoLaberinto {
  +valor
  +obtenervalor()
  +dibujarelemento()
}

class Pared {
}
class Jugador {
}
class EspacioLibre {
}
class meta {
}

Laberinto  -- ElementoLaberinto 
ElementoLaberinto <|-- Pared
ElementoLaberinto <|-- EspacioLibre
ElementoLaberinto <|-- Jugador
ElementoLaberinto <|-- meta
@enduml
